// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/MelleKoning/todohttp/models"
	mock "github.com/stretchr/testify/mock"
)

// TodoRepository is an autogenerated mock type for the TodoRepository type
type TodoRepository struct {
	mock.Mock
}

// Insert provides a mock function with given fields: todoItem
func (_m *TodoRepository) Insert(todoItem *models.TodoItem) (*models.TodoItem, error) {
	ret := _m.Called(todoItem)

	var r0 *models.TodoItem
	if rf, ok := ret.Get(0).(func(*models.TodoItem) *models.TodoItem); ok {
		r0 = rf(todoItem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TodoItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.TodoItem) error); ok {
		r1 = rf(todoItem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
